#!/usr/bin/env bash

# ------------------------------------------  FUNCTIONS AND CONSTANTS --------------------------------------------------

readonly COLOR_BLACK=0
readonly COLOR_RED=1
readonly COLOR_GREEN=2
readonly COLOR_YELLOW=3
readonly COLOR_BLUE=4
readonly COLOR_MAGENTA=5
readonly COLOR_CYAN=6
readonly COLOR_WHITE=7


function usage {
    echo "USAGE: "
    echo "     (sudo) phpv [OPTION]"
    echo ""
    echo "Possible options:"
    echo "    -v, v, --version        show current PHP version"
    echo "    -5, 5                   switch PHP version to 5.*"
    echo "    -7, 7                   switch PHP version to 7.*"
    echo ""
}


function currentVersion {
    ACTIVE_APACHE_MODULE_LOAD=`ls -l /etc/apache2/mods-enabled/php*.load | awk '{print $9}' | head -1`
    ACTIVE_APACHE_MOUDLE=`cat $ACTIVE_APACHE_MODULE_LOAD | grep LoadModule | awk '{print $3}'`

    echo ""
    textColor $COLOR_GREEN
    echo "---------------[ CURRENT VERSION ]---------------"
    textColor $COLOR_WHITE

    textColor $COLOR_BLUE
    echo -n " CLI: "
    textColor $COLOR_WHITE
    echo `php -v | head -1`

    textColor $COLOR_BLUE
    echo -n " APACHE MODULE: "
    textColor $COLOR_WHITE
    echo $ACTIVE_APACHE_MOUDLE
    echo ""
}


function textColor {
    tput setaf $1
}


function textUnderlineOn {
    tput smul
}


function textUnderlineOff {
    tput rmul
}


# ------------------------------------------------------  MAIN  --------------------------------------------------------


echo ""

if [[ ($1 == "-v") || ($1 == "v") || ($1 == "--version")]]; then
    currentVersion
    echo ""
    exit 0
fi

if [[ ($1 -eq 5) || ($1 == "-5") ]]; then
    MODULE_TO_DISABLE="php7.*"
    MODULE_TO_ENABLE="php5.*"
    CLI_MODULE_MASK="/usr/bin/php5*"
elif [[ ($1 -eq 7) || ($1 == "-7") ]]; then
    MODULE_TO_DISABLE="php5.*"
    MODULE_TO_ENABLE="php7.*"
    CLI_MODULE_MASK="/usr/bin/php7*"
else
    usage
    exit 0
fi


if [[ $EUID -ne 0 ]]; then
    echo "This script must be run as root" 1>&2
    exit 1
fi


textUnderlineOn
textColor $COLOR_BLUE;   echo -n "Switching to PHP version "
textColor $COLOR_YELLOW; echo -n "$1"
textColor $COLOR_BLUE;   echo    " ..."
textUnderlineOff
textColor $COLOR_WHITE;  echo ""


textUnderlineOn;         echo -n "Deactivating APACHE module "
textColor $COLOR_YELLOW; echo -n $MODULE_TO_DISABLE
textColor $COLOR_WHITE;  echo " ..."
textUnderlineOff

a2dismod $MODULE_TO_DISABLE
echo ""


textUnderlineOn;         echo -n "Activating APACHE module "
textColor $COLOR_YELLOW; echo -n $MODULE_TO_ENABLE
textColor $COLOR_WHITE;  echo " ..."
textUnderlineOff
a2enmod $MODULE_TO_ENABLE
echo ""


read -r -a CLI_MODULES <<< `ls -l $CLI_MODULE_MASK | awk '{print $9}' | sort -r`
CLI_MODULE=${CLI_MODULES[0]}

if [[ -n $CLI_MODULE ]]; then
    textUnderlineOn;         echo -n "Switching CLI module to "
    textColor $COLOR_YELLOW; echo -n $CLI_MODULE
    textColor $COLOR_WHITE;  echo " ..."
    textUnderlineOff

    rm -f /etc/alternatives/php
    ln -s $CLI_MODULE /etc/alternatives/php
    echo ""

else
    textColor $COLOR_RED;    echo -n "[ERROR!!!] CLI module for mask "
    textColor $COLOR_YELLOW; echo -n $CLI_MODULE_MASK
    textColor $COLOR_RED;    echo    "is not found"
fi

textUnderlineOn;             echo "Restarting APACHE ..."
textUnderlineOff;
service apache2 restart

echo ""
currentVersion
echo ""
